SELECT
    *
FROM
    `ZOMATODATA.FACT_TABLE`
WHERE
    COUNTRY = 'Europe';

SELECT
    *
FROM
    `ZOMATODATA.REST_DIM`
ORDER BY
    AVG_COST DESC;

SELECT
    *
FROM
    `ZOMATODATA.RATING_DIM`;

SELECT
    *
FROM
    `ZOMATODATA.LOCATION_DIM`;

SELECT
    *
FROM
    `ZOMATODATA.BOOKING_DELIVERY_DIM`;

#FIND RESTAURANTS WITH AVG COST FOR TWO GREATER THAN 3000.

SELECT
    R.REST_ID,
    R.REST_NAME,
    F.COUNTRY,
    R.AVG_COST
FROM
    `ZOMATODATA.REST_DIM` AS R
    INNER JOIN `ZOMATODATA.FACT_TABLE` AS F
    ON R.REST_ID = F.REST_ID
WHERE
    R.AVG_COST > 3000
ORDER BY
    R.AVG_COST DESC;

#FIND RESTAURANTS WITH AGGREGATE RATING GREATER THAN 3 AND VOTES GREATER THAN 100 IN INDIA.

SELECT
    R.REST_ID,
    R.REST_NAME,
    F.COUNTRY,
    RAT.AGG_RATING,
    RAT.VOTES
FROM
    `ZOMATODATA.REST_DIM` AS R
    JOIN `ZOMATODATA.FACT_TABLE` AS F
    ON R.REST_ID = F.REST_ID JOIN `ZOMATODATA.RATING_DIM`AS RAT
    ON F.REST_ID = RAT.REST_ID
WHERE
    RAT.REST_ID IN (
        SELECT
            REST_ID
        FROM
            `ZOMATODATA.RATING_DIM`
        WHERE
            AGG_RATING >= 3
            AND VOTES > 100
        ORDER BY
            AGG_RATING DESC
    )
ORDER BY
    RAT.AGG_RATING DESC;

#FIND TOP 5 RESTAURANTS IN EUROPE WITH HIGH AVG COST FOR TWO ALONG WITH THEIR CITY AND LOCALITY.

SELECT
    R.REST_ID,
    R.REST_NAME,
    R.AVG_COST,
    L.CITY,
    L.LOCALITY,
    F.COUNTRY
FROM
    `ZOMATODATA.REST_DIM` AS R
    JOIN `ZOMATODATA.FACT_TABLE` AS F
    ON R.REST_ID = F.REST_ID JOIN `ZOMATODATA.LOCATION_DIM`AS L
    ON F.REST_ID = L.REST_ID
WHERE
    F.COUNTRY = 'United States'
ORDER BY
    R.AVG_COST DESC LIMIT 5;

#FIND TOP 2 COUNTRIES WITH HIGHEST AVERAGE OF COST FOR PERSONS.

SELECT
    F.COUNTRY,
    FLOOR(AVG(R.AVG_COST)) AS AV_COST
FROM
    `ZOMATODATA.REST_DIM` AS R
    JOIN `ZOMATODATA.FACT_TABLE` AS F
    ON R.REST_ID = F.REST_ID
GROUP BY
    F.COUNTRY
ORDER BY
    AV_COST DESC LIMIT 2;

#CREATE TABLE FOR ANALYSIS.

CREATE OR REPLACE TABLE `ZOMATO-DATA-ANALYSIS.ZOMATODATA.TBL_ANALYTICS` AS (
SELECT
F.INDEX_ID,
F.REST_ID,
R.REST_NAME,
R.CUISINES,
R.AVG_COST,
R.PRICE_RANGE,
L.CITY,
L.ADDRESS,
L.LOCALITY,
L.LOCALITY_VERBOSE,
L.LATITUDE,
L.LONGITUDE,
RAT.AGG_RATING,
RAT.RATING_COLOR,
RAT.VOTES,
RAT.RATING_TEXT,
B.TABLE_BOOKING,
B.DELIVERING_NOW,
B.ONLINE_DELIVERY,
B.SWITCH_TO_ORDER_MENU,
F.COUNTRY_CODE,
F.COUNTRY
FROM
`ZOMATODATA.FACT_TABLE` AS F
JOIN `ZOMATODATA.REST_DIM` AS R ON F.REST_ID = R.REST_ID
JOIN `ZOMATODATA.LOCATION_DIM` AS L ON L.REST_ID = F.REST_ID
JOIN `ZOMATODATA.RATING_DIM` AS RAT ON RAT.REST_ID = F.REST_ID
JOIN `ZOMATODATA.BOOKING_DELIVERY_DIM` AS B ON B.REST_ID = F.REST_ID
ORDER BY F.INDEX_ID);